### ISSUE TITLE
Add Boost benchmark

### ISSUE THREAD

**Issue by jpetso** [gaspardpetit/base64#1]
Since it's so omnipresent, it would be great to have a test/benchmark for a Boost.Archive implementation, as listed in e.g. http://stackoverflow.com/questions/7053538/how-do-i-encode-a-string-to-base64-using-only-boost#7053808

I don't have a patch for it at this time, sorry!

**Comment by gaspardpetit** [comment]
Boost has been added. It gave the results you would expect from it: I had to pull 40MB of C++ dependencies, and it gave one of the worst result from the suite.... :)
