### ISSUE TITLE
Fix libb64 build

### ISSUE THREAD

**Issue by jpetso** [gaspardpetit/base64#3]
The libb64 submodule has no URL set so it's necessary to delete libs/libb64 before invoking `git submodule update --recursive --init`. Consequently, the cdecode.c/cencode.c files in the libb64 test folder can't find their respective header files, which breaks the build. A workaround is to remove the libb64 test from the project, but it would be better if it didn't fail in the first place.

**Comment by gaspardpetit** [comment]
This is now fixed, thanks to https://github.com/gaspardpetit/base64/pull/4
