### ISSUE TITLE
Update cppcodec

### ISSUE THREAD

**Issue by jpetso** [gaspardpetit/base64#5]
I released [cppcodec v0.2](https://github.com/tplgy/cppcodec/releases/tag/v0.2), which significantly improves performance compared to the initially benchmarked version, in no small part thanks to the motivational boost from your measurements. It would be great if the numbers in this repo and [on StackOverflow](https://stackoverflow.com/a/41094722/3149416) could reflect this change.

Thanks for your work and hopefully it's not too much to ask for an update :)

**Comment by gaspardpetit** [comment]
Sorry it took so long to circle back! I am updating the code and result, but I can already confirm that CppCodec now ranks amongst the top performing implementations!
